language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
 - vendor/bin/phpunit -v

before_script:
 - sudo apt-get -qq update > /dev/null
 - phpenv rehash > /dev/null
 - composer selfupdate --quiet
 - composer install --dev --prefer-dist

notifications:
  email:
    - kixxx1@gmail.com